export type AllowedStyles = [
    "color",
    "text-align",
    "background-color",
    "font-size",
    "font-weight",
    "font-style",
    "font-family",
    "padding",
    "margin",
    "border",
    "border-radius",
    "width",
    "height",
    "display",
    "align-items",
    "justify-content",
];

export const allowedStyles: AllowedStyles = [
    "color",
    "text-align",
    "background-color",
    "font-size",
    "font-weight",
    "font-style",
    "font-family",
    "padding",
    "margin",
    "border",
    "border-radius",
    "width",
    "height",
    "display",
    "align-items",
    "justify-content",
];
